PLAYER_HEALTH = 2
PLAYER_LIGHT = 5
PLAYER_STAKES = 5
PLAYER_DAMAGE = 1
PLAYER_GODMODE = False

DRACULA_DAMAGE = 1
DRACULA_HEALTH = 3
DRACULA_MOVES = 3

PLAYER_COUNT = 2
LAYOUT = 0

ROOM_WIDTH = 6
ROOM_HEIGHT = 4
PLAYER_OFFSET = {0 : (0, 0), 1 : (1, 0), 2 : (0, 1), 3 : (1, 1)}
WALL_CHAR = '#'
LIGHT_CHAR = 'L'
EMPTY_CHAR = ' '
DRACULA_CHAR = 'D'