PLAYER_MANUAL = True
DRACULA_MANUAL = False

PLAYER_HEALTH = 5
PLAYER_LIGHT = 3
PLAYER_STAKES = 2
PLAYER_DAMAGE = 1
PLAYER_GODMODE = False
PLAYER_GARLIC = 4
PLAYER_COUNT = 4
MAX_STAKES = 4
MAX_LIGHT = 5

DRACULA_DAMAGE = 1
DRACULA_HEALTH = 3
DRACULA_MOVES = 3

LAYOUT = 0
ROOM_WIDTH = 7
ROOM_HEIGHT = 5
PLAYER_OFFSET = {0 : (0, 0), 1 : (1, 0), 2 : (0, 1), 3 : (1, 1)}
WALL_CHAR = '|'
LIGHT_CHAR = 'L'
EMPTY_CHAR = ' '
DRACULA_CHAR = 'D'